### ISSUE TITLE
Generate FoV selection boxes with GUI

### ISSUE THREAD

**Issue by christianrickert** [WEHI-labatlab/HE_GUI#8]
I have the feeling that it might be easier to retrieve the box coordinates live from the user (with the current GUI), rather than having to pre-draw the boxes in another software and then save the updated image for loading into HE_GUI.

Have you explored drawing options with the current GUI?

**Comment by yokotenka** [comment]
The two main reasons we didn't implement this is because
1. In CaseCenter we are able to get a very high resolution image and see the structures of cells and interesting morphology
2. It is often times a Pathologist who decides on which areas are interesting. For them it is easier to use a familiar software such as CaseCenter to make these annotations.

Having said that, I do think this is a good idea and something we could have as an option.

**Comment by christianrickert** [comment]
Good points! - It seems to be fairly standard to ask pathologist to draw on images/slides, I've seen that quite a bit now.

**Comment by yokotenka** [comment]
I'm going to close this for now but maybe in the future we can implement this
